export const AreaList = {
  smt: [
    { label: "SMD", value: "smd" },
    { label: "PROCESS & REWORK", value: "process_rework" },
    { label: "WAVE", value: "wave" },
  ],
  eol: [
    { label: "EOL", value: "eol" },
    { label: "PRESS FIT & ICT", value: "press_fit_ict" },
  ],
  switch: [
    { label: "PW MAIN", value: "pw_main" },
    { label: "MIRROR MAIN", value: "mirror_main" },
    { label: "MULTI FUNCTION SUB", value: "multi_function_sub" },
    { label: "MULTI FUNCTION CPT", value: "multi_function_cpt" },
    { label: "MULTI FUNCTION MAIN", value: "multi_function_main" },
    { label: "SP2I WRC SUB", value: "sp2i_wrc_sub" },
    { label: "SP2I WRC MAIN", value: "sp2i_wrc_main" },
    { label: "QXI N MAIN", value: "qxi_n_main" },
    { label: "CPAD MAIN", value: "cpad_main" },
    { label: "BR2 WRC MAIN", value: "br2_wrc_main" },
    { label: "BC3 WRC MAIN", value: "bc3_wrc_main" },
    { label: "PASS MAIN", value: "pass_main" },
    { label: "PADDLE MAIN", value: "paddle_main" },
    { label: "INDICATOR MAIN", value: "indicator_main" },
    { label: "SSB MAIN", value: "ssb_main" },
    { label: "CONSOLE MAIN", value: "console_main" },
  ],
  keyset: [
    { label: "KEYSET MAIN", value: "keyset_main" },
    { label: "LOCK BODY MAIN", value: "lock_body_main" },
    { label: "ESCL MAIN", value: "escl_main" },
  ],
  quality_team: [],
  quality_assy_team: [],
  material_team: [],
  sales_team: [],
};
