export const DEFAULT_PROCESS_AREA = {
  smd: [
    "PCB LOADER",
    "LASER MARKING",
    "PCB CLEANER",
    "SOLDER PAST PRINTING",
    "SOLDER PAST INSPECTION",
    "PICK AND PLACE (MOUNTER)",
    "PCB INSPECTION (PRE-REFLOW)",
    "AOI INSPECTION",
    "STENCIL INSPECTION",
    "CHECK SHEET FILLING",
    "MODEL CHANGEOVER PROCESS",
    "LINE HANDLING",
    "ERM SCANNING",
    "3C & 5S MANAGEMENT",
  ],
  process_rework: [
    "STENCIL INSPECTION",
    "REFLOW PROFILE",
    "SOLDER PASTE PROCESSING",
    "SQUEEGEE INSPECTION",
    "REWORK PART INSPECTION",
    "MACHINE PROGRAMMING",
    "ROOTCAUSE ANALYZING & CORRECTION",
    "FIRST PART VALIDATION",
    "DAILY PROCESS AUDIT",
    "DAILY CHECK SHEET VERIFICATION",
    "COMPONENT PREPARATION",
    "DATA ENTRY",
    "REWORK PROCESS",
    "HANDLING THE FINE PITCH COMPONENTS",
    "REWORK INSPECTION",
    "3C & 5S MANAGEMENT",
    "CRN AND CONVERSION PART HANDLING",
  ],
  wave: [
    "COMPONENT STUFFING",
    "CLUNCHING PROCESS",
    "SCREWING PROCESS",
    "FLUX APPLICATOR",
    "PCBA INSPECTION",
    "REWORK",
    "DROSS REMOVING",
    "CHECK SHEET FILLING",
    "LINE HANDLING",
    "PALLET MANAGEMENT",
    "3C & 5S MANAGEMENT",
    "MODEL CHANGEOVER PROCESS",
  ],
  eol: [
    "MODEL CHANGEOVER",
    "PROGRAM SELECTION",
    "JIG SETUP",
    "KEY INTER CHANGE",
    "PIN VISION",
    "VISUAL INSPECTION",
    "BRACKET SELECTION",
    "CHECK SHEET FILLING",
    "3C & 5S MANAGEMENT",
    "SUB ASSEMBLY",
    "PROGRAM WRITING",
    "DARK CURRENT",
    "FINAL INSPECTION",
    "THERMAL PASTE APPLYING",
    "SCREWING",
    "FG LABEL SCANNING",
  ],
  press_fit_ict: [
    "PCBA LOADING",
    "PROGRAM SELECTION",
    "PROGRAM TEACHING",
    "VISUAL INSPECTION",
    "UNLOADER",
    "PIN DIAGRAM VERIFICATION",
    "CHECK SHEET FILLING",
    "MODEL CHANGEOVER",
    "UV INSPECTION",
    "PCBA ROUTING",
    "CASE ASSEMBLY",
    "VISUAL INSPECTION",
    "HEAT CAULKING",
    "BARCODE SCANNING & LABEL PASTING",
    "COATING REFILING AND VERIFICATION",
  ],
  pw_main: [
    "PRISM ASSEMBLY",
    "PUSHER ASSEMBLY",
    "GREASE APPLY & KNOB ASSEMBLY",
    "PCB CLEANING & RUBBER CONTACT ASSEMBLY",
    "BODY AND PCBA CPT ASSEMBLY",
    "SCREW ASSEMBLY",
    "VISION TESTER & EOL",
    "PACKING",
  ],
  mirror_main: [
    "PCB CLEANING & RUBBER CONTACT ASSEMBLY",
    "GREASE APPLY & KNOB ASSEMBLY",
    "BODY AND PCBA CPT ASSEMBLY",
    "SCREW ASSEMBLY",
    "VISION TESTER & EOL",
    "PACKING",
  ],
  multi_function_sub: [
    "Fog Knob CPT Assy",
    "Detent piece Assy",
    "Contact holder CPT Assy",
    "HOLDER & DETENT ASS'Y",
    "Light bracket ARM assy",
    "Light lever upper knob clamp pin Assy",
    "INT Knob CPT Assy",
    "INT detent piece Assy",
    "WIPER bracket ARM assy",
    "WIPER lever upper knob clamp pin Assy",
  ],
  multi_function_cpt: [
    "FOG KNOB ASSY",
    "INT KNOB ASSY",
    "MIDDLE KNOB ASSY",
    "UPPER COVER SCREW & LOWER COVER ASSY",
    "CONTACT HOLDER & STATOR ASSY",
    "UPPER KNOB PIN ASSY",
    "DETENT PIECE & BRACKET CPT ASSY",
  ],
  multi_function_main: [
    "GREASE ASSEMBLY & KNOB ASSEMBLY",
    "BODY AND PCBA CPT ASSEMBLY",
    "SCREW ASSEMBLY",
    "EOL TESTING",
    "VI & PACKING",
  ],
  sp2i_wrc_sub: [
    "CASE ASSEMBLY",
    "GREASE APPLY & KNOB ASSEMBLY",
    "PCB CLEANING & RUBBER CONTACT ASSEMBLY",
  ],
  sp2i_wrc_main: [
    "LH SUB CPT & RH SUB CPT",
    "BEZEL ASSEMBLE",
    "SCREW ASSEMBLY",
    "VISION TESTER & EOL",
    "PACKING",
  ],
  qxi_n_main: [
    "PCB CLEANING & RUBBER CONTACT ASSEMBLY",
    "GREASE APPLY & KNOB ASSEMBLY",
    "BODY AND PCBA CPT ASSEMBLY",
    "SCREW ASSEMBLY",
    "VISION TESTER & EOL",
    "PACKING",
  ],
  cpad_main: [
    "PRISM ASSEMBLY",
    "GREASE APPLY & KNOB ASSEMBLY",
    "BODY AND PCBA CPT ASSEMBLY",
    "SCREW ASSEMBLY",
    "VISION TESTER & EOL",
    "PACKING",
  ],
  br2_wrc_main: [
    "PCB CLEANING & RUBBER CONTACT ASSEMBLY",
    "GREASE APPLY & KNOB ASSEMBLY",
    "BODY AND PCBA CPT ASSEMBLY",
    "SCREW ASSEMBLY",
    "VISION TESTER & EOL",
    "PACKING",
  ],
  bc3_wrc_main: [
    "PCB CLEANING & RUBBER CONTACT ASSEMBLY",
    "GREASE APPLY & KNOB ASSEMBLY",
    "BODY AND PCBA CPT ASSEMBLY",
    "SCREW ASSEMBLY",
    "VISION TESTER & EOL",
    "PACKING",
  ],
  pass_main: [
    "PCB CLEANING & RUBBER CONTACT ASSEMBLY",
    "GREASE APPLY & KNOB ASSEMBLY",
    "BODY AND PCBA CPT ASSEMBLY",
    "EOL",
    "PACKING",
  ],
  paddle_main: [
    "PCB CLEANING & RUBBER CONTACT ASSEMBLY",
    "GREASE APPLY & KNOB ASSEMBLY",
    "BODY AND PCBA CPT ASSEMBLY",
    "SCREW ASSEMBLY",
    "EOL",
    "PACKING",
  ],
  indicator_main: [
    "BODY & CASE ASSEMBLY",
    "COVER & PRISM ASSEMBLY",
    "VISION TESTER & EOL",
    "PACKING",
  ],
  ssb_main: [
    "Grease apply on case & Antenna coil",
    "PCBA Contact pad cleaning and Case Assembly",
    "Deco ring Assy",
    "Antenna Coil Assy",
    "VISION TESTER & EOL",
    "PACKING",
  ],
  console_main: [
    "PRISM & BEZEL ASSEMBLY",
    "GREASE APPLY & KNOB ASSEMBLY",
    "PCBA & CASE ASSEMBLY",
    "VISION TESTER & EOL",
    "PACKING",
  ],
  keyset_main: [
    "Shutter Cover Caulking assy",
    "Rotator CPT Assy",
    "Lock Plate & Lock spring Assy",
    "Spiroll Pin Pressing Assy",
    "Lock Cylinder Assy",
    "Return Spring assy",
    "E-Ring Assy",
    "Antenna coil Assy",
    "Cover Screwing assy",
    "VI & Packing",
    "Keyset EOL Testing",
  ],
  lock_body_main: ["VI & Packing", "Lock body EOL Testing", "packing"],
  escl_main: [
    "Spacer & Worm Wheel Gear assy On Motor",
    "Motor CPT on ECU Case assy",
    "Spring Pin Pressing on Lock Bar & Lock stopper Assy",
    "Lock Body Greasing assy",
    "Cover Base Assy",
    "Spiroll pin pressing Assy",
    "Screw Fastening Assy",
    "Bracket Assy on Lock Body",
    "EOL Testing & Packing",
  ],
};
