export const DEFAULT_PROCESS_AREA = {
  key_set: [
    "PODMONTAŻ",
    "KEY SET MONTAŻ",
    "D/LOCK MONTAŻ",
    "KEY SET TEST",
    "LOCK BODY MONTAŻ",
    "LOCK BODY TEST",
    "P.A.B. MONTAŻ",
    "P.A.B TEST",
    "LDC MONTAŻ",
    "LDC TEST",
    "LS/LP MASZYNA",
    "LS/LP STANOWISKO KONTROLNE",
  ],
  "c_pad/0fd": [
    "Mirror podmontaż",
    "Mirror montaż",
    "Mirror test",
    "PW rear/assist montaż",
    "PW rear/assist test",
    "PW Main montaż",
    "PW Main test",
    "Facia/Hazard montaż",
    "Facia/Hazard test",
    "Paddle montaż",
    "Paddle test",
    "EPB montaż",
    "EPB test",
    "IMS montaż",
    "IMS test",
    "Console CD montaż",
    "Console CD test",
    "Console SBC montaż",
    "Console SBC test",
  ],
  multifunction: [
    "MULTIFUNCTION PODMONTAŻ",
    "MF FINAL MONTAŻ",
    "MF FINAL TEST",
    "MF LEVER LUTOWANIE 1",
    "MF LEVER LUTOWANIE 2",
    "MF LEVER MONTAŻ",
    "MF LEVER TEST",
  ],
  remocon: [
    "HAZARD NX4 MONTAŻ",
    "HAZARD NX4 TEST",
    "CPAD (all) MONTAŻ",
    "CPAD ZGRZEWANIE HLLD ",
    "CPAD (all) TEST",
    "REMOCON CD MONTAŻ",
    "REMOCON CD TEST",
    "REMOCON PDE MONTAŻ",
    "REMOCON PDE TEST",
    "REMOCON NQ5 MONTAŻ",
    "REMOCON NQ5 TEST",
  ],
  "pw/console": [
    "NQ5 CONSOLE DRIVE MODE MONTAŻ",
    "NQ5 CONSOLE DRIVE MODE TEST",
    "NQ5 SEAT WARMER SBW/SBC MONTAŻ",
    "NQ5 SEAT WARMER SBW/SBC TEST",
    "CONSOLE PDe +  MT NQ5 + MT NX4 MONTAŻ",
    "CONSOLE PDe +  MT NQ5 + MT NX4 TEST",
    "ARMREST NX4 + S/WARMER  CD/NQ5 MONTAŻ",
    "ARMREST NX4 + S/WARMER  CD/NQ5 TEST",
    "EPB NX4 MONTAŻ",
    "EPB NX4 TEST",
    "CONSOLE SBW NX4 MONTAŻ",
    "CONSOLE SBW NX4 TEST",
  ],
  renault: [
    "MSCL",
    "TX ASSY",
    "XDD DOOR LOCK",
    "XJI/XJF DOOR LOCK",
    "MSCL HOUSING ASSY",
    "MSCL ASSY",
  ],
  smt: [
    "SMT Vacuum Loader",
    "SMT Laser Marking Machine",
    "SMT Scanning Conveyor",
    "SMT Screen Printer",
    "SMT Solder Paste Inspector",
    "SMT Chip Mounter",
    "SMT Reflow",
    "SMT Automatic Optical Inspection",
    "SELECTIVE SOLDERING Automatic Screw Fastener",
    "SELECTIVE SOLDERING Selective Soldering",
    "SELECTIVE SOLDERING BSI",
    "COATING Machine",
    "ROUTER Machine",
    "WAVE Automatic Flux  Spray  System",
    "WAVE Automatic Solder WAVE",
    "EOL",
    "EOL Auto camera",
  ],
};
